config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'

  resources :posts do
    resources :comments
  end
  resources :authors, only: %i[new create show]
  resources :votes

  get 'signup', to: 'authors#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :vote

  validates :email, presence: true, uniqueness: true

  def full_name
    first_name + " " + last_name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author
  has_many :votes
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments, dependent: :destroy

  has_one_attached :image

  is_impressionable

  def self.search(search)
    where(("title LIKE ? OR content LIKE ?"), "%#{search}%", "%#{search}%")
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :author
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_author

  def current_author
    if session[:author_id]
      @current_author ||= Author.find(session[:author_id])
    else
      @current_author = nil
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(author_params)
    if @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_variables, only: %i[edit update destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)
    @comment.save
    if @comment.save
      redirect_to post_path(@comment.post)
      flash[:success] = 'You have created comment'
    else
      redirect_to root_path
    end
  end

  def edit
    redirect_to post_path(@post) if !current_author.present? || @comment.author_id != current_author.id || Time.now - @comment.created_at > 3600
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
      flash[:success] = 'You have updated comment'
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :author_id)
  end

  def set_variables
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :set_post, only: %i[show edit update destroy]

  impressionist actions: [:show], unique: [:session_hash]

  def index
    @posts = params[:search] ? Post.search(params[:search]) : Post.all.sort_by(&:updated_at)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    if current_author.present?
      @post = Post.new
    else
      redirect_to signin_path
    end
  end

  def create
    @post = Post.create(post_params)
    @post.save!
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    redirect_to post_path(@post) if !current_author.present? || @post.author_id != current_author.id
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :author_id,
                                 :image, :views_count)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path if current_author.present?
  end

  def create
    author = Author.find_by_email(params[:session][:email])
    if author && author.authenticate(params[:session][:password])
      session[:author_id] = author.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:author_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: %i[vote_up vote_down update]

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.create(vote_params)
    @vote.save
    if @vote.save
      redirect_to post_path(@vote.comment.post)
    else
      redirect_to 'new'
    end
  end

  def vote_up; end

  def vote_down; end

  def update
    if @vote.update(vote_params)
      redirect_to post_path(@vote.comment.post)
    end
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:comment_id, :author_id, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def author_full_name(first_name, last_name)
    "#{first_name} #{last_name}"
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/new.html.erb
<h1>Sign Up</h1>

<%= form_for @author do |f| %>
  <div class="form-field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="form-field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="form-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit 'Sing up', class: 'btn btn-dark-blue' %>
<% end %>

app/views/authors/show.html.erb
<%= @author.first_name %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :author_id, value: current_author.id %>
  <div class="form-field">
    <label>Add comment:</label>
    <%= f.text_area :content %>
  </div>
  <%= f.submit class: 'btn btn-dark-blue' %>
<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorPostsProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<%= render 'shared/nav-bar' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="post-form-page">
  <%= form_for @post do |f| %>
  <%= f.hidden_field :author_id, value: current_author.id %>
    <div class="form-field">
      <label>Title:</label>
      <%= f.text_field :title %>
    </div>
    <div class="form-field">
      <label>Content:</label>
      <%= f.text_area :content %>
    </div>
    <div class="form-field">
      <label>Image:</label>
      <%= f.file_field :image %>
    </div>
    <%= f.submit class: 'btn btn-dark-blue' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="posts-page">
  <%= link_to 'Create new post', new_post_path, class: 'btn btn-dark-blue' %>

  <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
    <div class="d-flex m-b-20">
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
      <%= submit_tag 'Search', class: 'btn btn-light-blue m-0' %>
    </div>
  <% end %>

  <div class="posts row no-gutters">
    <% @posts.each do |post| %>
      <div class="post">
        <div class="image" style="background-image: url('<%= url_for(post.image) if post.image.attached? %>')"></div>
        <div class="content-block">
          <p class="title"><%= post.title %></p>
          <p class="content"><%= post.content %></p>
          <p><%= author_full_name(post.author.first_name, post.author.last_name) %></p>
          <div class="row no-gutters justify-content-center">
            <%= link_to 'Show', post_path(post), class: 'btn btn-light-blue' %>
            <% if current_author.present? && post.author_id == current_author.id %>
              <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-light-blue' %>
              <%= button_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-light-blue' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post-show-page">
  <%= link_to 'All posts', posts_path, class: 'btn btn-dark-blue' %>
  <div class="image" style="background-image: url('<%= url_for(@post.image) if @post.image.attached? %>')"></div>
  <p class="title"><%= @post.title %></p>
  <p class="content"><%= @post.content %></p>
  <div class="row no-gutters justify-content-between">
    <p class="text-14 grey-text"><%= author_full_name(@post.author.first_name, @post.author.last_name) %>
      , <%= distance_of_time_in_words(Time.now, @post.created_at) %></p>
    <p><i class="far fa-eye"></i> <%= @post.impressionist_count %></p>
  </div>

  <% if current_author.present? %>
    <div class="comment-form">
      <%= render 'comments/form' %>
    </div>
  <% end %>

  <% @comments.each do |comment| %>
    <div class="comment-block">
      <div class="comment" title="<%= comment.created_at %>">
        <p><%= comment.content %></p>
        <p class="text-14 grey-text"><%= author_full_name(comment.author.first_name, comment.author.last_name) %>,
          <%= distance_of_time_in_words(Time.now, comment.created_at) %>
          <%= comment.votes.map(&:value).sum %>
          <% if comment.created_at != comment.updated_at %>
            , Edited
          <% end %>
        </p>
      </div>
      <div>
        <% if current_author.present? && current_author == comment.author && Time.now - comment.created_at <= 3600 %>
          <%= link_to 'Edit', edit_post_comment_path(@post, comment), class: 'btn btn-light-blue' %>
          <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, class: 'btn btn-light-blue' %>
        <% end %>
      </div>
    </div>
    <br/>
  <% end %>
</div>

app/views/shared/_nav-bar.html.erb
<nav class="nav-bar">
  <%= link_to 'Sign in', signin_path, class: 'btn btn-dark-blue' if !current_author.present? %>
  <%= link_to 'Sign up', signup_path, class: 'btn btn-dark-blue' if !current_author.present? %>
  <%= link_to 'Sign out', signout_path, class: 'btn btn-dark-blue' if current_author.present? %>
</nav>